# https://github.com/googleapis/repo-automation-bots/tree/master/packages/sync-repo-settings
# Rules for master branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `master`
- pattern: master
  requiredStatusCheckContexts:
    - 'Kokoro'
    - 'cla/google'
    - 'Samples - Lint'
    - 'Samples - Python 3.6'
    - 'Samples - Python 3.7'
    - 'Samples - Python 3.8'
