# config.yaml

# The name of the service, used for variable names and comments.
service_name: "bigquery"

# A list of paths to the source code files to be parsed.
# Globs are supported.
source_files:
  - "autogen/google/cloud/bigquery_v2/services/dataset_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/job_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/model_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/project_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/routine_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/row_access_policy_service/client.py"
  - "autogen/google/cloud/bigquery_v2/services/table_service/client.py"

# Filtering rules for classes and methods.
filter:
  classes:
    # Only include classes with these suffixes.
    include_suffixes:
      - "Client"
  methods:
    # Include methods with these prefixes.
    include_prefixes:
      - "batch_delete_"
      - "cancel_"
      - "create_"
      - "delete_"
      - "get_"
      - "insert_"
      - "list_"
      - "patch_"
      - "undelete_"
      - "update_"
    # Exclude methods with these prefixes.
    exclude_prefixes:
      - "get_mtls_endpoint_and_cert_source"

# A list of templates to render and their corresponding output files.
templates:
  - template: "autogen/scripts/microgenerator/bigqueryclient.py.j2"
    output: "autogen/google/cloud/bigquery_v2/services/centralized_service/client.py"
  # - template: "test_bigqueryclient.py.j2"
  #   output: "tests/unit/test_bigqueryclient.py"
