# config.yaml

# The name of the service, used for variable names and comments.
service_name: "bigquery"

# A list of paths to the source code files to be parsed.
# Globs are supported.
source_files:
  services:
    - "google/cloud/bigquery_v2/services/dataset_service/client.py"
    - "google/cloud/bigquery_v2/services/job_service/client.py"
    - "google/cloud/bigquery_v2/services/model_service/client.py"
    - "google/cloud/bigquery_v2/services/project_service/client.py"
    - "google/cloud/bigquery_v2/services/routine_service/client.py"
    - "google/cloud/bigquery_v2/services/row_access_policy_service/client.py"
    - "google/cloud/bigquery_v2/services/table_service/client.py"
  types:
    - "google/cloud/bigquery_v2/types/dataset.py"
    - "google/cloud/bigquery_v2/types/job.py"
    - "google/cloud/bigquery_v2/types/model.py"
    - "google/cloud/bigquery_v2/types/project.py"
    - "google/cloud/bigquery_v2/types/routine.py"
    - "google/cloud/bigquery_v2/types/row_access_policy.py"
    - "google/cloud/bigquery_v2/types/table.py"


# Filtering rules for classes and methods.
filter:
  classes:
    # Only include classes with these suffixes.
    include_suffixes:
      - "ServiceClient"
      - "Request"
    # Exclude classes with these suffixes.
    exclude_suffixes:
      - "BigQueryClient"
  methods:
    # Include methods with these prefixes.
    include_prefixes:
      - "batch_delete_"
      - "cancel_"
      - "create_"
      - "delete_"
      - "get_"
      - "insert_"
      - "list_"
      - "patch_"
      - "undelete_"
      - "update_"
    # Exclude methods with these prefixes.
    exclude_prefixes:
      - "get_mtls_endpoint_and_cert_source"
    overrides:
      patch_table:
        request_class_name: "UpdateOrPatchTableRequest"
      patch_dataset:
        request_class_name: "UpdateOrPatchDatasetRequest"

# A list of templates to render and their corresponding output files.
# A list of templates to render and their corresponding output files.
templates:
  - template: "templates/client.py.j2"
    output: "google/cloud/bigquery_v2/services/centralized_service/client.py"
  - template: "templates/_helpers.py.j2"
    output: "google/cloud/bigquery_v2/services/centralized_service/_helpers.py"
  - template: "templates/__init__.py.j2"
    output: "google/cloud/bigquery_v2/services/centralized_service/__init__.py"

post_processing_templates:
  - template: "templates/post-processing/init.py.j2"
    target_file: "google/cloud/bigquery_v2/__init__.py"
    add_imports:
      - "from .services.centralized_service import BigQueryClient"
    add_to_all:
      - "BigQueryClient" 